LOCAL_PATH := $(call my-dir)

# libARSAL
include $(CLEAR_VARS)

LOCAL_MODULE := LIBARSAL-prebuilt
LOCAL_SRC_FILES := $(TARGET_ARCH_ABI)/libarsal.a

include $(PREBUILT_STATIC_LIBRARY)

# libNetworkAL
include $(CLEAR_VARS)

LOCAL_MODULE := LIBARNETWORKAL-prebuilt
LOCAL_SRC_FILES := $(TARGET_ARCH_ABI)/libarnetworkal.a

include $(PREBUILT_STATIC_LIBRARY)

# libNetwork
include $(CLEAR_VARS)

LOCAL_MODULE := LIBARNETWORK-prebuilt
LOCAL_SRC_FILES := $(TARGET_ARCH_ABI)/libarnetwork.a

include $(PREBUILT_STATIC_LIBRARY)

# WRAPPER_LIB
include $(CLEAR_VARS)

LOCAL_C_INCLUDES:= $(LOCAL_PATH)/include
LOCAL_LDLIBS := -llog
LOCAL_MODULE := libarnetwork_android
LOCAL_SRC_FILES := ARNETWORK_JNIManager.c  ARNETWORK_JNIIOBufferParam.c
LOCAL_STATIC_LIBRARIES := LIBARNETWORK-prebuilt LIBARSAL-prebuilt LIBARNETWORKAL-prebuilt
include $(BUILD_SHARED_LIBRARY)

